# PYTHON PARA DATA SCIENCE - NUMPY

# Verificando versão

In [96]:
!python -V

Python 3.7.13


# Trabalhando com Arrays Numpy

In [97]:
import numpy as np
import random as rm

In [98]:
km = np.loadtxt('carros-km.txt', dtype = float)

In [99]:
anos = np.loadtxt('carros-anos.txt', dtype = int)

In [100]:
km_media = km / (2022 - anos)

In [101]:
type(km_media)

numpy.ndarray

# Operações matemáticas


## Adição (+)

In [102]:
2+2

4

## Subtração (-)

In [103]:
2-2

0

## Multiplicação (*)

In [104]:
2*3

6

## Divisão (/) e (//)

In [105]:
10/3

3.3333333333333335

In [106]:
10 // 3

3

## Exponenciação (**)

In [107]:
2**3

8

## Resto da Divisão (%)

In [108]:
10 % 3

1

In [109]:
10 % 2

0

## Expressões matemáticas

In [110]:
5 * 2 + 3 * 2

16

In [111]:
(5 * 2) + (3 * 2)

16

In [112]:
5 * (2 + 3) * 2

50

# A Variável _

```
No modo interativo, o ultimo resultado impresso é a tribuido à variavél _
```



In [113]:
5*2

10

In [114]:
_ + 3*2

16

In [115]:
_ / 2

8.0

# Variáveis 

## Operações com variáveis

In [116]:
ano_atual = 2022
ano_fabricacao = 2003
km_total = 44410.0

In [117]:
ano_atual

2022

In [118]:
ano_fabricacao

2003

In [119]:
km_total

44410.0

## $$km_{média} = \frac {km_{total}}{(Ano_{atual} - Ano_{fabricação})}$$

In [120]:
km_media = km_total / (ano_atual - ano_fabricacao)

In [121]:
ano_atual = 2022
ano_fabricacao = 2003
km_total = 44410.0
km_media = km_total / (ano_atual - ano_fabricacao)
km_total += km_media
km_total


46747.36842105263

## Declaração multipla

In [122]:
ano_atual, ano_fabricacao, km_total = 2019, 2003, 44410.0

In [123]:
ano_atual

2019

In [124]:
ano_fabricacao

2003

In [125]:
km_total


44410.0

# Tipos de Dados

## Numeros

In [126]:
ano_atual = 2019

In [127]:
type(ano_atual)

int

In [128]:
km_total = 44410.0

In [129]:
type(km_total)

float

## Booleano

In [130]:
zero_km = False

In [131]:
type(zero_km)

bool

## Strings

In [132]:
nome = 'Jetta Variant'
nome

'Jetta Variant'

In [133]:
nome = "Jetta Variant"
nome

'Jetta Variant'

In [134]:
nome = 'Jetta "Variante"'
nome

'Jetta "Variante"'

In [135]:
carro = ''' 
Nome 
Idade 
Nota
'''
carro

' \nNome \nIdade \nNota\n'

In [136]:
type(carro)

str

## None

In [137]:
quilometragem = None
quilometragem

In [138]:
type(quilometragem)

NoneType

# Conversão de tipos

In [139]:
a, b, c, d = 10, 20, 'Python é ', 'Legal'

In [140]:
type(a)

int

In [141]:
type(b)

int

In [142]:
type(c)

str

In [143]:
type(d)

str

In [144]:
a + b

30

In [145]:
c + d

'Python é Legal'

In [146]:
c + str(a)

'Python é 10'

In [147]:
type(str(a))

str

In [148]:
float(a)

10.0

In [149]:
var = 3.141592

In [150]:
type(var)

float

In [151]:
int(var)

3

In [152]:
var = 3.99

In [153]:
int(var)

3

# Identação, comentários e formatação de strings

## Identação

In [154]:
ano_atual = 2022
ano_fabricacao = 2019

if (ano_atual == ano_fabricacao):
  print('Verdadeiro')
else:
  print('Falso')

Falso


## Comentários

In [155]:
# Isso é um comentário
ano_atual = 2022
ano_atual

2022

In [156]:
# Isso
# é um
# comentário
ano_atual = 2022
ano_atual

2022

In [157]:
''' 
Isso é um comentario
'''
ano_atual = 2022
ano_atual

2022

In [158]:
# Definindo variáveis
ano_atual = 2022
ano_fabricacao = 2019

'''
Estrutura condicional 
'''
if (ano_atual == ano_fabricacao): # Testando se condição é verdadeira
  print('Verdadeiro')
else:                             # Testando se condição é falsa
  print('Falso')

Falso


## Formatação de String

### str.format()

In [159]:
print('Olá, {}'.format('Lucas'))

Olá, Lucas


In [160]:
print('Olá, {}! Este é seu acesso de numero {}'.format('Lucas', 32))

Olá, Lucas! Este é seu acesso de numero 32


In [161]:
nome = 'Lucas'
acesso = 32
print('Olá, {}! Este é seu acesso de número {}'.format(nome, acesso))

Olá, Lucas! Este é seu acesso de número 32


f-String

In [162]:
nome = 'Lucas'
acesso = 32
print(f'Olá, {nome}! Este é seu acesso de número {acesso}')

Olá, Lucas! Este é seu acesso de número 32


# Trabalhando com Listas

## Criando listas

Listas são sequências **mutáveis** que são utilizadas para armazenar coleções de itens, geralmente homogêneos. Podem ser construídas de várias formas:
```
- Utilizando um par de colchetes: [ ], [ 1 ]
- Utilizando um par de colchetes com itens separados por vírgulas: [ 1, 2, 3 ]
```

In [163]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [164]:
type(Acessorios)

list

## Lista com tipos de dados variados

In [165]:
carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 88078.64]
carro_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimídia', 'Teto panorâmico', 'Freios ABS'], 106161.94]

In [166]:
carro_1

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
 88078.64]

In [167]:
carro_2

['Passat',
 'Motor Diesel',
 1991,
 5712.0,
 False,
 ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
 106161.94]

In [168]:
carros = [carro_1, carro_2]

In [169]:
carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

In [170]:
type(carros)

list

## Operações com Lista

### X in A 

In [171]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [172]:
"Rodas de liga" in Acessorios

True

In [173]:
"4 X 4" in Acessorios

False

In [174]:
"Rodas de liga" not in Acessorios

False

In [175]:
"4 X 4" not in Acessorios

True

### A + B

In [176]:
A = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']
B = ['Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']

In [177]:
A

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']

In [178]:
B

['Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [179]:
A + B

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

### len(x)

In [180]:
len(Acessorios)

8

In [181]:
len(A)

4

## Seleções de listas

### A[n]

In [182]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [183]:
Acessorios[0]

'Rodas de liga'

In [184]:
Acessorios[1]

'Travas elétricas'

In [185]:
Acessorios[-1]

'Sensor de chuva'

In [186]:
carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

In [187]:
carros[0]

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
 88078.64]

In [188]:
carros[0][0]

'Jetta Variant'

In [189]:
carros[0][-2]

['Rodas de liga', 'Travas elétricas', 'Piloto automático']

In [190]:
carros[0][-2][1]

'Travas elétricas'

### A[n:j]

In [191]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [192]:
Acessorios[2:5]

['Piloto automático', 'Bancos de couro', 'Ar condicionado']

In [193]:
Acessorios[2:]

['Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [194]:
Acessorios[:5]

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado']

## Metodos de Lista

In [195]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

### A.sort()
Ordena a lista A

In [196]:
Acessorios.sort()

In [197]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

### A.append(x)
Adiciona o elemento x no final da lista A

In [198]:
Acessorios.append('4 X 4')

In [199]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 X 4']

### A.pop(i)
Remove e retorna o elemento de indice i da lista A

In [200]:
Acessorios.pop()

'4 X 4'

In [201]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [202]:
Acessorios.pop(3)

'Rodas de liga'

### A.copy()
Cria uma cópia da lista A

In [203]:
Acessorios_2 = Acessorios
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [204]:
Acessorios_2.append('4 X 4')

In [205]:
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 X 4']

In [206]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 X 4']

In [207]:
Acessorios_2 = Acessorios.copy()

In [208]:
Acessorios_2.append('4 X 4')

In [209]:
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 X 4',
 '4 X 4']

In [210]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 X 4']

# Estrutura de repetição e condicional

## Loops com listas

In [211]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [212]:
for item in Acessorios:
  print(item)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva


## List Comprehensions

In [213]:
list(range(0, 11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [214]:
for i in range(11):
  print(i ** 2)

0
1
4
9
16
25
36
49
64
81
100


In [215]:
quadrado = []
for i in range(11):
  quadrado.append(i ** 2)

quadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [216]:
[i ** 2 for i in range(11)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

## Loops Aninhados

In [217]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [218]:
for lista in dados:
  print(lista)

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento']
['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']


In [219]:
for lista in dados:
  for item in lista:
    print(item)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva
Central multimídia
Teto panorâmico
Freios ABS
4 X 4
Painel digital
Piloto automático
Bancos de couro
Câmera de estacionamento
Piloto automático
Controle de estabilidade
Sensor crepuscular
Freios ABS
Câmbio automático
Bancos de couro
Central multimídia
Vidros elétricos


In [220]:
Acessorios = []

for lista in dados:
  for item in lista:
    Acessorios.append(item)

In [221]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

In [222]:
list(set(Acessorios))

['Controle de estabilidade',
 'Câmbio automático',
 'Rodas de liga',
 'Vidros elétricos',
 'Sensor de chuva',
 'Piloto automático',
 'Travas elétricas',
 'Sensor de estacionamento',
 'Freios ABS',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Teto panorâmico',
 '4 X 4',
 'Painel digital',
 'Sensor crepuscular',
 'Ar condicionado',
 'Central multimídia']

In [223]:
list(set([item for lista in dados for item in lista]))

['Controle de estabilidade',
 'Câmbio automático',
 'Rodas de liga',
 'Vidros elétricos',
 'Sensor de chuva',
 'Piloto automático',
 'Travas elétricas',
 'Sensor de estacionamento',
 'Freios ABS',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Teto panorâmico',
 '4 X 4',
 'Painel digital',
 'Sensor crepuscular',
 'Ar condicionado',
 'Central multimídia']

# Instrução if

In [224]:
dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [225]:
zero_km_y = []
for lista in dados:
  if lista[2] == True:
    zero_km_y.append(lista)
zero_km_y

[['DS5', 2019, True], ['A5', 2019, True]]

In [226]:
zero_km_n = []
for lista in dados:
  if lista[2] == False:
    zero_km_n.append(lista)
zero_km_n

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [227]:
[lista for lista in dados if lista[2] == True]

[['DS5', 2019, True], ['A5', 2019, True]]

In [228]:
[lista for lista in dados if lista[2] == False]

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

### Instruções *if-else* e *if-elif-else

In [229]:
zero_km_y, zero_km_n = [], []

for lista in dados:
  if lista[2] == True:
    zero_km_y.append(lista)
  else:
    zero_km_n.append(lista)

In [230]:
zero_km_y

[['DS5', 2019, True], ['A5', 2019, True]]

In [231]:
zero_km_n

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [232]:
print('AND')
print(f'(True and True) o resultado é: {True and True}')
print(f'(True and False) o resultado é: {True and False}')
print(f'(False and True) o resultado é: {False and True}')
print(f'(False and False) o resultado é: {False and False}')

AND
(True and True) o resultado é: True
(True and False) o resultado é: False
(False and True) o resultado é: False
(False and False) o resultado é: False


In [233]:
print('OR')
print(f'(True or True) o resultado é: {True or True}')
print(f'(True or False) o resultado é: {True or False}')
print(f'(False or True) o resultado é: {False or True}')
print(f'(False or False) o resultado é: {False or False}')

OR
(True or True) o resultado é: True
(True or False) o resultado é: True
(False or True) o resultado é: True
(False or False) o resultado é: False


In [234]:
A, B, C = [], [], []
for lista in dados:
  if lista[1] <= 2000:
    A.append(lista)
  elif lista[1] > 2000 and lista[1] <= 2010: #elif 2000 < lista[1] <= 2010
    B.append(lista)
  else:
    C.append(lista)
    

In [235]:
A

[['Passat', 1991, False], ['Crossfox', 1990, False]]

In [236]:
B

[['Jetta Variant', 2003, False],
 ['Aston Martin DB4', 2006, False],
 ['Série 3 Cabrio', 2009, False]]

In [237]:
C

[['DS5', 2019, True],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

# NUMPY BÁSICO

Numpy é a abreviação de Numerical Python e é um dos pacotes mais importantes para processamento numérico em Python. Numpy oferece a base para a maioria dos pacotes de aplicações científicas que utilizem dados numéricos em Python (estruturas de dados e algoritmos). Pode-se destacar os seguintes recursos que o pacote Numpy contém:

- Um poderoso objeto array multidimensional;
- Funções matemáticas sofisticadas para operações com arrays sem a necessidade de utilização de laços *for*;
- Recursos de algebra linear e geração de números aleatórios

Além de seus óbvios usos científicos, o pacote NumPy também é muito utilizado em análise de dados como um eficiente contêiner multidimensional de dados genéricos para transporte entre diversos algoritmos e bibliotecas em Python.

**Versão:** 1.16.5

**Instalação:** https://scipy.org/install.html

**Documentação:** https://numpy.org/doc/1.16/

# **PACOTES**

Existem diversos pacotes Python disponíveis para download na internet. Cada pacote tem como objetivo a solução de determinado tipo de problema e para isso são desenvolvidos novos tipos, funções e métodos.

Alguns pacotes são bastante utilizados em um contexto de ciência de dados como por exemplo:

- Numpy
- Pandas
- Scikit-learn
- Matplotlib

Alguns pacotes não são distribuídos com a instalação default do Python. Neste caso devemos instalar os pacotes que necessitamos em nosso sistema para podermos utilizar suas funcionalidades.

## importando todo o pacote

In [238]:
import numpy

In [239]:
numpy.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [240]:
import numpy as np

In [241]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## importando parte do pacote

In [242]:
from numpy import arange

In [243]:
arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Criando arrays Numpy

## A partir de listas

In [244]:
km = np.array([1000, 2300, 4978, 1500])

In [245]:
km

array([1000, 2300, 4978, 1500])

In [246]:
type(km)

numpy.ndarray

In [247]:
km.dtype

dtype('int64')

## A partir de dados externos

In [248]:
km = np.loadtxt(fname = 'carros-km.txt', dtype=int)

In [249]:
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [250]:
km.dtype

dtype('int64')

## Arrays com 2 dimensões

In [251]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [252]:

Acessorios = np.array(dados)

In [253]:
Acessorios

array([['Rodas de liga', 'Travas elétricas', 'Piloto automático',
        'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento',
        'Sensor crepuscular', 'Sensor de chuva'],
       ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4',
        'Painel digital', 'Piloto automático', 'Bancos de couro',
        'Câmera de estacionamento'],
       ['Piloto automático', 'Controle de estabilidade',
        'Sensor crepuscular', 'Freios ABS', 'Câmbio automático',
        'Bancos de couro', 'Central multimídia', 'Vidros elétricos']],
      dtype='<U24')

In [254]:
km.shape

(258,)

In [255]:
Acessorios.shape

(3, 8)

## Comparando desempenho com listas

In [256]:
np_array = np.arange(1000001)

In [257]:
py_list = list(range(1000001))

In [258]:
%time for _ in range(100): np_array *= 2

CPU times: user 136 ms, sys: 1.19 ms, total: 137 ms
Wall time: 144 ms


In [259]:
%time for _ in range(100): py_list = [x * 2 for x in py_list]

CPU times: user 10.5 s, sys: 2.96 s, total: 13.5 s
Wall time: 14 s


# Operações aritméticas com arrays Numpy

In [260]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

In [261]:
# idade = 2019 - anos

In [262]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [263]:
idade = 2019 - anos

In [264]:
idade

array([16, 28, 29,  0, 13])

## Operações entre arrays

In [265]:
km_media = km / idade

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [266]:
km_media

array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

## Operações entre arrays de duas dimensões

In [267]:
dados = np.array([km,anos])

In [268]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [269]:
dados.shape

(2, 5)

In [270]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [271]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

In [272]:
km_media = dados[0] / (2019 - dados[1])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [273]:
km_media

array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

# Seleções com Arrays Numpy

In [274]:
dados = np.array([[44410., 5712., 37123., 0., 25757.],[ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [275]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [276]:
contador = np.arange(10)

In [277]:
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [278]:
item = 6
index = item - 1
contador[index]

5

In [279]:
dados[1][2]

1990.0

In [280]:
dados[1, 2]

1990.0

In [281]:
contador[1:4]

array([1, 2, 3])

In [282]:
contador[1:8:2]

array([1, 3, 5, 7])

In [283]:
contador[::2]

array([0, 2, 4, 6, 8])

In [284]:
contador[1::2]

array([1, 3, 5, 7, 9])

In [285]:
dados[:,1:3]

array([[ 5712., 37123.],
       [ 1991.,  1990.]])

In [286]:
dados[:,1:3][0] / (2019 - dados[:,1:3][1])

array([ 204.        , 1280.10344828])

## Indexação com array booleano

In [287]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [288]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [289]:
contador[contador > 5]

array([6, 7, 8, 9])

In [290]:
contador[[False, False, False, False, False, False,  True,  True,  True,
        True]]

array([6, 7, 8, 9])

In [291]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [292]:
dados[:, dados[1] > 2000][0] / (2019 - dados[:, dados[1] > 2000][1])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([2775.625     ,           nan, 1981.30769231])

# Atributos e Métodos de Arrays Numpy

In [293]:
dados = np.array([[44410., 5712., 37123., 0., 25757.],[ 2003.,  1991.,  1990.,  2019.,  2006.]])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

## ndarray.shape
Retorna uma tupla com as dimensões array

In [294]:
dados.shape

(2, 5)

## ndarray.ndim
Retorna o numero de dimensões array

In [295]:
dados.ndim

2

## ndarray.size
Retorna o numero de elementos do array

In [296]:
dados.size

10

## ndarray.dtype
Retorna o tipo de dado dos elementos do array

In [297]:
dados.dtype

dtype('float64')

## ndarray.T
Retorna o array transposto, isto é converte linhas em colunas e vice versa

In [298]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [299]:
dados.transpose()

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

## ndarray.tolist()
Retorna o array como uma lista Python

In [300]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

## ndarray.reshape(shape[,order])
Retorna um array que contem os mesmos dados com uma nova forma

In [301]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [302]:
contador.reshape((5, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [303]:
contador.reshape((5, 2), order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [304]:
contador.reshape((5, 2), order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [305]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [306]:
info_carros = km + anos
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [307]:
np.array(info_carros).reshape((5, 2), order='F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

## ndarray.resize(new_shape[,refcheck])
Altera a forma e o tamanho do array

In [308]:
dados_new = dados.copy()
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [309]:
dados_new.resize((3, 5), refcheck = False)

In [310]:
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [311]:
dados_new[2] = dados_new[0] / (2019 - dados_new[1])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [312]:
dados_new

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2775.625     ,   204.        ,  1280.10344828,            nan,
         1981.30769231]])

# Estatistica com arrays Numpy


In [314]:
anos = np.loadtxt(fname = 'carros-anos.txt', dtype = int)
km = np.loadtxt(fname = 'carros-km.txt')
valor = np.loadtxt(fname = 'carros-valor.txt')

In [315]:
anos.shape

(258,)

In [316]:
km.shape

(258,)

In [317]:
valor.shape

(258,)

In [331]:
dataset = np.column_stack((anos, km, valor))
dataset

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [319]:
dataset.shape

(258, 3)

## np.mean()
Retorna a média dos elementos do array ao longo do eixo especificado

In [327]:
np.mean(dataset, axis = 0)

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [ ]:
np.mean(dataset, axis = 0)

In [333]:
np.mean(dataset[0:,1:], axis = 0)

array([44499.41472868, 98960.51310078])

## np.std()
Retorna o desvio padrão dos elementos do array ao longo do eixo especificado

In [334]:
np.std(dataset)

48982.75759118537

In [335]:
np.std(dataset[0:,1:], axis = 0)

array([39859.82699005, 29754.10115039])

## ndarray.sum()
Retorna a soma dos elementos do array ao longo do eixo especificado

In [337]:
dataset.sum(axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [338]:
dataset[:, 1].sum()

11480849.0

In [339]:
dataset[0:,1:].sum(axis = 0)

array([11480849.        , 25531812.37999999])

## np.sum()
Retorna a soma dos elementos do array ao longo do eixo especificado

In [340]:
np.sum(dataset, axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [341]:
np.sum(dataset[0:,1:], axis = 0)

array([11480849.        , 25531812.37999999])